[phases.setup]
    nixPkgs = ['nodejs', 'python3']
    aptPkgs = ['build-essential', 'libudev-dev']

[build]
    buildCommand = "npm install -g pnpm && pnpm install --frozen-lockfile && pnpm run prisma-generate && pnpm run build:backend"

[deploy]
    startCommand = "node --max-old-space-size=2048 --experimental-require-module ./apps/backend/dist/apps/backend/src/main.js"
